### ISSUE TITLE
Does not seem to be a scikit-learn estimator

### ISSUE THREAD

**Issue by marutilai** [ZhiningLiu1998/imbalanced-ensemble#19]
Getting the error in the code provided in examples

![image](https://user-images.githubusercontent.com/88403147/218265254-b18817e8-9989-4151-9906-3f35a03b7389.png)

Coming from this line: clf.fit(X_train, y_train) from this notebook https://github.com/ZhiningLiu1998/imbalanced-ensemble/blob/main/examples/classification/plot_classifier_comparison.py

**Comment by ZhiningLiu1998** [comment]
Hi,

Thanks for pointing this out. Since sklearn version 1.2, the `base_estimator` is deprecated and will be removed in 1.4. They renamed this parameter to `estimator` (See [HERE](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostClassifier.html#sklearn.ensemble.AdaBoostClassifier)). Thus I recently made some commits to accommodate this change, you can try clone and installing the latest version locally:
> $ git clone https://github.com/ZhiningLiu1998/imbalanced-ensemble.git
> $ cd imbalanced-ensemble
> $ pip install .

The example should work once you install the latest version.

After all the updates are done, I'll release a new version to PyPi.

**Comment by marutilai** [comment]
Thanks @ZhiningLiu1998. I tried testing again and got this new error message:

<img width="934" alt="image" src="https://user-images.githubusercontent.com/88403147/218273343-991c91bb-9be3-4caf-9595-02d66f5e5bea.png">

**Comment by marutilai** [comment]
Thanks, Zhining! Found another issue trying the latest commit

https://github.com/ZhiningLiu1998/imbalanced-ensemble/issues/19#issuecomment-1426838265

**Comment by ZhiningLiu1998** [comment]
Oh thank you, I'll look into it now

**Comment by ZhiningLiu1998** [comment]
Hi there, I just make a commit to fix this. I tested the BalancedRandomForestClassifier and the plot_classifier_comparison.py locally and they work fine, please try it and let me know if the issue persists. Thanks.

**Comment by marutilai** [comment]
It works now. Thanks @ZhiningLiu1998!
