### ISSUE TITLE
Bug :AttributeError: can't set attribute

### ISSUE THREAD

**Issue by leaphan** [ZhiningLiu1998/imbalanced-ensemble#6]
hello ,when i use the code as follow,the will be some errors, EasyEnsembleClassifier was used

from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import balanced_accuracy_score
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from imbalanced_ensemble.ensemble import EasyEnsembleClassifier
from collections import Counter

X, y = make_classification(n_classes=2, class_sep=2,
    weights=[0.1, 0.9], n_informative=3, n_redundant=1, flip_y=0,
    n_features=20, n_clusters_per_class=1, n_samples=1000, random_state=10)
print('Original dataset shape %s' % Counter(y))
# Original dataset shape Counter({{1: 900, 0: 100}})
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
bbc = EasyEnsembleClassifier(random_state=42)
bbc.fit(X_train, y_train)
EasyEnsembleClassifier(...)
y_pred = bbc.predict(X_test)
print(y_pred)

Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/pythonProject5/test-easy.py", line 16, in <module>
    bbc.fit(X_train, y_train)
  File "C:\Users\Administrator\PycharmProjects\pythonProject5\venv\lib\site-packages\imbalanced_ensemble\utils\_validation.py", line 602, in inner_f
    return f(**kwargs)
  File "C:\Users\Administrator\PycharmProjects\pythonProject5\venv\lib\site-packages\imbalanced_ensemble\ensemble\under_sampling\easy_ensemble.py", line 275, in fit
    return self._fit(X, y, 
  File "C:\Users\Administrator\PycharmProjects\pythonProject5\venv\lib\site-packages\imbalanced_ensemble\utils\_validation.py", line 602, in inner_f
    return f(**kwargs)
  File "C:\Users\Administrator\PycharmProjects\pythonProject5\venv\lib\site-packages\imbalanced_ensemble\ensemble\_bagging.py", line 359, in _fit
    n_samples, self.n_features_ = X.shape
AttributeError: can't set attribute

**Comment by ZhiningLiu1998** [comment]
![image](https://user-images.githubusercontent.com/26108487/143427601-10387f30-ff0f-42f3-8027-09ec598b45a8.png)

Hi leaphan,

Thanks for your interest, but I cannot reproduce your error.
I completely reinstalled IMBENS from PyPI in my local environment and ran your example code, but nothing happened.
This may be caused by the inconsistent python version.
I'm using python 3.8.5, it would be helpful for me to locate the error and debug if you can provide more detailed system information, e.g., the version of python and main dependencies like NumPy, scipy, sklearn, etc.

**Comment by leaphan** [comment]
thanks for your reply. i'm using python 3.8

![1637838498(1)](https://user-images.githubusercontent.com/35593707/143430794-2647ac98-40f3-438a-bc90-482a4beba56f.png)

**Comment by leaphan** [comment]
python3.8.8

![1637839798(1)](https://user-images.githubusercontent.com/35593707/143433955-304b113e-07be-4639-900d-eddc80aa5d85.png)

**Comment by leaphan** [comment]
![1637840500(1)](https://user-images.githubusercontent.com/35593707/143435462-2b016173-1673-416d-9a0f-4207d0d23ad8.png)

**Comment by ZhiningLiu1998** [comment]
Thanks for your help! I reproduced the error using python 3.8.

I've confirmed that this is caused by the property naming (`n_features_`), which is now depreciated in `sklearn`.
This issue should have been fixed by my recent commit.
You can now install from this Github repository:
```
$ git clone https://github.com/ZhiningLiu1998/imbalanced-ensemble.git
$ cd imbalanced-ensemble
$ pip install .
```
and EasyEnsemble as well as other bagging-based methods should work well.

Please feel free to contact me if you have any further questions or find any other bugs.

Best,
Zhining

**Comment by leaphan** [comment]
> Thanks for your help! I reproduced the error using python 3.8.
> 
> I've confirmed that this is caused by the property naming (`n_features_`), which is now depreciated in `sklearn`. This issue should have been fixed by my recent commit. You can now install from this Github repository:
> 
> ```
> $ git clone https://github.com/ZhiningLiu1998/imbalanced-ensemble.git
> $ cd imbalanced-ensemble
> $ pip install .
> ```
> 
> and EasyEnsemble as well as other bagging-based methods should work well.
> 
> Please feel free to contact me if you have any further questions or find any other bugs.
> 
> Best, Zhining

thank u very much,i got the result with your help!

**Comment by ZhiningLiu1998** [comment]
@all-contributors please add @leaphan for the bug reporting
